-- INSERT INTO department (name)
-- VALUES
--   ('JS Juggernauts'),
--   ('Heroes of HTML'),
--   ('Git Gurus');

-- INSERT INTO roles (title, salary, department_id)
-- VALUES
--   ('Ronald', 'Firbank', 1, 1),
--   ('Virginia', 'Woolf', 1, 1),
--   ('Piers', 'Gaveston', 1, 0),
--   ('Charles', 'LeRoi', 2, 1),
--   ('Katherine', 'Mansfield', 2, 1),
--   ('Dora', 'Carrington', 3, 0),
--   ('Edward', 'Bellamy', 3, 0),
--   ('Montague', 'Summers', 3, 1),
--   ('Octavia', 'Butler', 3, 1),
--   ('Unica', 'Zurn', NULL, 1);

--   INSERT INTO employee (first_name, last_name, role_id, manager_id)
-- VALUES
--   ('James', 'Fraser', 'jf@goldenbough.edu'),
--   ('Jack', 'London', 'jlondon@ualaska.edu'),
--   ('Robert', 'Bruce', 'rbruce@scotland.net'),
--   ('Peter', 'Greenaway', 'pgreenaway@postmodern.com'),
--   ('Derek', 'Jarman', 'djarman@prospectcottage.net'),
--   ('Paolo', 'Pasolini', 'ppasolini@salo.com'),
--   ('Heathcote', 'Williams', 'hwilliams@bafta.com'),
--   ('Sandy', 'Powell', 'spowell@oscars.com'),
--   ('Emil', 'Zola', 'ezola@requin.com'),
--   ('Sissy', 'Coalpits', 'scoalpits@greenaway.com'),
--   ('Antoinette', 'Capet', 'acapet@dontloseyourhead.com'),
--   ('Samuel', 'Delany', 'sdelany@dhalgren.com'),
--   ('Tony', 'Duvert', 'tduvert@frenchletters.edu'),
--   ('Dennis', 'Cooper', 'dcooper@georgemiles.com'),
--   ('Monica', 'Bellucci', 'mbell@irreverisble.net'),
--   ('Samuel', 'Johnson', 'sjohnson@boswell.com'),
--   ('John', 'Dryden', 'jdryden@restoration.net'),
--   ('Alexander', 'Pope', 'apope@cambridge.uk.edu'),
--   ('Lionel', 'Johnson', 'ljohnson@darkangel.com'),
--   ('Aubrey', 'Beardsley', 'abeardsely@wilde.net'),
--   ('Tulse', 'Luper', 'tluper@films.net'),
--   ('William', 'Morris', 'wmorris@victoriana.com'),
--   ('George', 'Shaw', 'gshaw@labor.uk'),
--   ('Arnold', 'Bennett', 'abennett@poemsgalore.com');